### PR TITLE
Add InReplyTo and References as possible header fields to emails

### PR DESCRIPTION
**Pull request by MartinThoma**
Related to https://stackoverflow.com/q/45630004/562769
See

* In-Reply-To: https://tools.ietf.org/html/rfc4021#page-10
* References: https://tools.ietf.org/html/rfc4021#page-11

### CODE REVIEW

**Comment by MartinThoma** [comment]
I'm not sure if the names / types of fields I used are correct.

**Comment by ecederstrand** [comment]
https://msdn.microsoft.com/en-us/library/office/aa580994(v=exchg.150).aspx and https://msdn.microsoft.com/en-us/library/office/aa565671(v=exchg.150).aspx state that these fields are strings, so the field type should be OK.

The fields are in the wrong place in the FIELDS list. You need to insert them in the same order as the list in
https://msdn.microsoft.com/en-us/library/office/aa494306(v=exchg.150).aspx Otherwise some Exchange versions will not accept the XML.

**Comment by MartinThoma** [comment]
Should I just move `InReplyTo` up into the Item class before `IsDraft`? I'm not too sure what this class is for.

**Comment by MartinThoma** [comment]
Hm. The `InReplyTo` leads to an internal server error. Having only the `References` works.

**Comment by ecederstrand** [comment]
`InReplyTo` is a field on the `Item` element and should be added to the `Item.FIELDS` list, right after the 'importance' field (see https://msdn.microsoft.com/en-us/library/office/aa580790(v=exchg.150).aspx).

`References` is a field on the `Message` element and should be added to the `Message.FIELDS` list, right after the 'is_response_requested' field (see https://msdn.microsoft.com/en-us/library/office/aa494306(v=exchg.150).aspx).

**Comment by ecederstrand** [comment]
Fixed in https://github.com/ecederstrand/exchangelib/commit/a714ac1eb1c1fac9c4548fe8b3f8f383ceb191c1 instead, as I wanted to run the test suite, and Travis doesn't do that for PR's. Thanks!

**Comment by MartinThoma** [comment]
Nice! When do you plan to upload the new version on PyPI?

(By the way: Did you hear about [`git tag`](https://git-scm.com/book/en/v2/Git-Basics-Tagging)? It would make it easier to see which changes came with which version.)

**Comment by ecederstrand** [comment]
I'll upload a new version in the next couple of days, when I can get the test suite in a more stable condition. And yes, I have some reading to do re. git tags :-) See also #181

**Pull request closed without merging**
