### PR TITLE
Support folder:PermissionSet field (#574)

### PR DESCRIPTION
**Pull request by cranbar**

### CODE REVIEW

**Comment by ecederstrand** [comment]
Thanks for your hard work!

I'm really busy the next days but will review the PR sometime next week.

**Comment by cranbar** [comment]
This issue isn't urgent, but I wanted to follow up, @ecederstrand.  Let me know if you have any feedback or requested changes.

**Comment by ecederstrand** [comment]
Hi @cranbar Just to let you know I haven't forgotten you :-) Some unexpected events came up, but I expect to test and review within the next week.

**Comment by ecederstrand** [comment]
Hi @cranbar I pushed some changes to the master branch with partial support for the PermissionSet field. Your version is more complete so I'll add your improvements manually.

**Comment by ecederstrand** [comment]
Changes in this MR were added manually in https://github.com/ecederstrand/exchangelib/commit/f93c2605d81e0f8719434615082f76c24692b75d

**Comment by cranbar** [comment]
Thanks, @ecederstrand !

**Pull request closed without merging**
