### PR TITLE
add Fields for Meeting Messages	

### PR DESCRIPTION
**Pull request by frennkie**
It would be great if the handling of meeting messages could be extended/completed. I have started looking into it. Could you let me know if this is going in the right direction?!

Missing:
* [ ] implement units/integration tests for added compontents
* [x] complete README.rst with usage for added functionality

### CODE REVIEW

**Comment by frennkie** [comment]
@ecederstrand I have to admit that a lot of the code in this PR was simply copied over from other parts of the code base. I also have not yet managed to read and completely understand how all parts of this lib work together...  

Could you explain to me or point me to some documentation that helps me understand some details... e.g. for the Fields in `items.py` there are settings for `is_read_only`, `is_read_only_after_send` and `is_required`. How do I know how to set these?!

**Comment by frennkie** [comment]
Another question: In this PR I implemented `exchangelib.items.AcceptItem()` class which has the method `send()` can be used to accept a meeting invitation. I'm currently using it in my demo/test code like this:

 ```python
# auto accept all invites
for item in messages:
    if isinstance(item, MeetingRequest):
        accept_msg = AcceptItem(
            account=account,
            folder=None,
            sensitivity='Private',
            reference_item_id=ReferenceItemId(id=item.item_id, changekey=item.changekey),
            body='sure I'll come',
        )
        accept_msg.send()
```

Is this how it is intended to be done? Or should `exchangelib.items.MeetingRequest` get a `accept()` method (that wraps `exchangelib.items.AcceptItem()`) so that we could simply run `item.accept(body='sure I'll come')`?!

**Comment by ecederstrand** [comment]
The `is_read_only`, `is_read_only_after_send` and `is_required` are either derived from documentation on MSDN, or are trial-and-error where we start by setting them all to `False`. The test suite will then check if the field is in fact writable or can be ommitted.

**Comment by ecederstrand** [comment]
Regarding the `accept()` method, I think it's best to have both. `AcceptItem.send()` would be the low-level method allowing full control. This is consistent with other classes. `MeetingRequest.accept()` would be a convenience method accepting the most common arguments. It creates an `AcceptItem` object and sends it.

**Comment by ecederstrand** [comment]
This looks very good! I think the only thing missing is a simple test of sending a meeting request and responding with an accept, decline or tentatively_accept message.

**Comment by frennkie** [comment]
Sounds good... :-) I'll try to find some time to look into the tests.

I still have a few things where I could use some feedback:
* [ ] `exchangelib.items.ITEM_CLASSES` - should I add any of the new classes to that? 
* [ ] I'm currently catching `ErrorCalendarIsNotOrganizer` and `ErrorCalendarMeetingRequestIsOutOfDate`.. should this be done in the lib? Or is it in the responsibility of the devs using exchangelib to handle all exceptions
* [ ] What should in your opinion `exchangelib.items.AcceptItem.send()` return? Exchange send two Results: a `CalendarItem` and a `MeetingRequest`.

**Comment by frennkie** [comment]
I'm struggling a bit with the tests.. :-/

> This looks very good! I think the only thing missing is a simple test of sending a meeting request and responding with an accept, decline or tentatively_accept message.

Are you talking about mocking or doing real interaction with an exchange server? I have seen and am using the `settings.yml` file. But as far as I see it this only uses one account one the server. Sending a MeetingRequest (and then responding to) it only seems to be possible by using two separate account, right?

**Comment by ecederstrand** [comment]
Oh, yes, you're right. Testing meeting requests will only work if the test server has at least two accounts.

If you want, you're welcome to expand the test suite to add an extra account in `settings.yml` and let the test suite skip your test if `settings.yml` does not contain two accounts. Alternatively, test manually and provide a short writeup of how to handle meeting requests in the README. The latter should be there anyway.

**Comment by ecederstrand** [comment]
I think I answered all questions in https://github.com/ecederstrand/exchangelib/pull/369#issuecomment-377786350 inline in code comments, except:

> What should in your opinion exchangelib.items.AcceptItem.send() return? Exchange send two Results: a CalendarItem and a MeetingRequest.

I don't really have an opinion on this. Just make sure any exceptions are raised :-) You could return both, if that makes sense. Then the caller can decide which one to use in further processing.

**Comment by ecederstrand** [comment]
Hi @frennkie I'm unsure what the status of this is? I haven't tested the branch, but as far as I can see it's only missing a section in the README and an entry in the CHANGELOG? Feel free to speak up if you need anything from me.

**Comment by frennkie** [comment]
@ecederstrand I'll work some more on it tonight (e.g. `README`). I will also rebase the changes you made since my fork (e.g. the fix for #384 as I also ran into this..).

**Comment by frennkie** [comment]
I updated the ``CHANGELOG`` and the ``README`` and did manual testing with the setup that I have available. So far the changes seem to be working as expected. 

I have not been able to implement automated tests against a real Exchange (using two accounts). I would really appreciate if you could take over that part.. :-)

**Comment by ecederstrand** [comment]
Thanks! I won't be able to add automated tests for the time being because my hosted test server only has one account and it costs $$ to get a bigger setup. So manual testing will have to do for now :-)

**Comment by ecederstrand** [comment]
Thanks for your fantastic work!

**Pull request merged**
