### PR TITLE
Several updates related to Streaming Notifications

### PR DESCRIPTION
**Pull request by spmsh**
Several updates related to Streaming Notifications.

- updated account.py with the max_connections param and pass it on to discovery.py and cache.py as well (to keep config consistent with the value coming from Account)
- updated errors.py to group all Subscription related errors together with a SubscriptionMessageError class
- updated base.py to raise a SubscriptionMessageError whenever there is an issue with subscriptions
- updated protocol.py to allow an unlimited no. of session based on max_connections param. 0 means no limit (create a new session each time)
- updated common.py to add the BackEndOverrideCookie to the session in order to properly maintain affinity (and fixed a typo)
- updated common.py to save the BackEndOverrideCookie from the session on Subscribing requests
- updated get_streaming_events.py and explicitly added streaming and prefer_affinity flags as well as getting the corresponding error class on subscription related issues
- updated subscribe.py and unsubscribe.py to add prefer_affinity flags
- updated util.py to remove the <t:String> as this is rejected by EWS on Subscription Request (malformed error)

Results of these changes makes the streaminig notifications non-blocking and new events will arrive as they are "streamed" (instead of waiting the end of the connection defined by the connection_timeout on account.calendar.get_streaming_events(subscription_ids, connection_timeout=30)).

It has been tested in my own application using O365, OAUTH2 and impersonation, and maintaining affinity according to MS recommandations (https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-maintain-affinity-between-group-of-subscriptions-and-mailbox-server).

I have tested this with a 100+ mailboxes, grouped in 13 differents groups and it has been running fine for days now (and still running).

### CODE REVIEW

**Comment by omidontop** [comment]
Any updates on this PR?

**Comment by ecederstrand** [comment]
I've been watching this PR from the side. I'm sure it contains lots of important fixes. From my point of view, it needs to be broken into smaller, more contained collections of changes to make it easier to reason about and back out changes if that turns out to be necessary. And we need to have comments and test coverage of the changes.

**Comment by nburlett** [comment]
If nothing else, the change to `GetStreamingEvents.__init__` to set `self.streaming` is needed to make streaming work on the current release as it fixes #1025

**Comment by ecederstrand** [comment]
Some notes after reviewing the code here:

* I committed a fix for the `GetStreamingEvents.streaming` change in https://github.com/ecederstrand/exchangelib/commit/57fbaa5b4dec645a4522f6106745f723c55b1161
* `max_connections` cannot be a per-account setting because a `Protocol` is shared between accounts on the same server
* Which problem are you trying to solve that requires having a per-server configuration of `max_connections` for `AutodiscoverProtocol` instead of just setting `AutodiscoverProtocol .SESSION_POOLSIZE`?
* I don't see the use for unlimited sessions. Exchange servers will not be happy to be swamped with TCP connections, and you can just set an insanely high number if you really need it
* Defaulting to only using sessions once is wasteful, IMHO. It's only relevant if you e.g. have a memory leak in lower-level networking code. It's easy to set MAX_SESSION_USAGE_COUNT if you want this behaviour.
* The `from multiprocessing import Lock` is a mis-merge
* The `elem.text = v` change will rewrite the element text for every element in the passed list, which is definitely wrong.
* The affinity changes look Ok. I'll happily merge that if it's extracted to a separate PR with a simple test.

**Comment by ecederstrand** [comment]
I brought in improvements to affinity cookie handling in https://github.com/ecederstrand/exchangelib/commit/38b9e2d8210c5a901c36dd5838ad10358e4b128a loosely based on the changes made in this PR.

**Comment by omidontop** [comment]
> I brought in improvements to affinity cookie handling in [38b9e2d](https://github.com/ecederstrand/exchangelib/commit/38b9e2d8210c5a901c36dd5838ad10358e4b128a) loosely based on the changes made in this PR.

Thank you so much! Are there any releases scheduled with these fixes?

**Comment by ecederstrand** [comment]
Her you go: https://pypi.org/project/exchangelib/4.6.2/

**Comment by omidontop** [comment]
> Her you go: https://pypi.org/project/exchangelib/4.6.2/

Thanks Erik, much appreciated!

**Comment by ecederstrand** [comment]
@spmsh Does this PR still have changes you would like to merge into exchangelib?

**Comment by spmsh** [comment]
> @spmsh Does this PR still have changes you would like to merge into exchangelib?

apologies guys, I was away for a while and didn't check my messages on here.
I'm still struggling a bit to merge my changes with your exchangelib without the "unlimited sessions" bit.

Since I'm grouping inboxes by affinity, say for 100 inboxes you could have more than a dozen groups, which will be blocked by the number of sessions at some point (max sessions reached - waiting for session). This also happens when I say a huge number, after several days (or weeks), I'll reach the limit.

With unlimited sessions I have no issues, solution is working fine for days without being rejected by O365 because of too many connections.

Or the other part I'm looking for, maybe my sessions are not correctly released after use, I'm trying to manualy call retire_session/release_session at the end of my calls see if there are any improvements.

Beyond that, all the rest is good to go for a good streaming subscriptions.

**Comment by ecederstrand** [comment]
If you end up running out of sessions, it must mean that sessions are never returned to the session pool. That is done in `Protocol.release_session()` which, in the case of `GetStreamingEvents`, happens in `GetStreamingEvents.stop_streaming()`. The only way I can see that method not being called is if the generator returned by `Folder.get_streaming_events()` is never fully consumed. Could that be the case in your code?

**Comment by ecederstrand** [comment]
I just pushed https://github.com/ecederstrand/exchangelib/commit/4c43bad5860e3d5a6d6b646e3c9748b7dfa3e618 which may fix the session leakage, although I haven't been able to trigger it unless I:

1. Don't fully consume `Folder.get_streaming_events()`
2. Keep a reference around to the generator returned by `Folder.get_streaming_events()` so it can't be garbage collected.

**Pull request closed without merging**
